Preference screens
Samsonroyal/Clearpath pull request #36
Opened 2024-05-19 15:31 UTC by CodesByBaafogAyo

Created Screen

2024-05-19 17:28 UTC, Samsonroyal approved these changes
Good to merge

2024-05-19 17:28 UTC, Samsonroyal commented
> Good to merge

@bright2kwame awaiting your review to merge

2024-05-20 11:22 UTC, bright2kwame requested changes
button1, button2 can we give a more descriptive names here ??

2024-05-21 22:50 UTC, bright2kwame requested changes

2024-05-21 22:50 UTC, bright2kwame commented on clearpath/app/[dashboard]/preferences/page.css
> +.button2 {
lets name this in a desriptive way

2024-05-21 22:50 UTC, bright2kwame commented on clearpath/app/[dashboard]/preferences/page.css
> +.button {
same here, lets name this descriptively

2024-05-22 18:07 UTC, CodesByBaafogAyo commented on clearpath/app/[dashboard]/preferences/page.css
> +.button2 {
Ok Bright

2024-05-22 23:44 UTC, closed without merging

2024-05-22 23:44 UTC, Samsonroyal commented
This PR has been resolved.